name: Test Build Workflow

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to test (leave empty for all)"
        required: false
        default: ""
        type: choice
        options:
          - ""
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-13"
          - "macos-latest"

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            artifact_name: pse-scraper-linux-x64
          - os: windows-latest
            platform: windows-x64
            artifact_name: pse-scraper-windows-x64.exe
          - os: macos-13 # Intel x64 runner
            platform: macos-x64
            artifact_name: pse-scraper-macos-x64
          - os: macos-latest # ARM64 runner (now default)
            platform: macos-arm64
            artifact_name: pse-scraper-macos-arm64

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    # Skip builds if a specific platform is requested and this isn't it
    if: ${{ github.event.inputs.platform == '' || matrix.os == github.event.inputs.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set UTF-8 encoding (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV
          echo "PYTHONUTF8=1" >> $env:GITHUB_ENV
          chcp 65001
        shell: pwsh

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with dev --no-interaction

      - name: Build executable
        run: |
          poetry run python build_executable.py --clean

      - name: Verify executable exists
        run: |
          ls -la releases/
          if [ ! -f "releases/${{ matrix.artifact_name }}" ]; then
            echo "Error: Executable not found at releases/${{ matrix.artifact_name }}"
            exit 1
          fi

      - name: Test executable (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x releases/${{ matrix.artifact_name }}
          ./releases/${{ matrix.artifact_name }} --version
          ./releases/${{ matrix.artifact_name }} --help

      - name: Test executable (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:PYTHONIOENCODING = "utf-8"
          $env:PYTHONUTF8 = "1"
          chcp 65001 > $null
          & ".\releases\${{ matrix.artifact_name }}" --version
          & ".\releases\${{ matrix.artifact_name }}" --help
        shell: pwsh

      - name: Get file info
        run: |
          echo "File size and info:"
          ls -lh releases/

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.artifact_name }}
          path: releases/${{ matrix.artifact_name }}
          retention-days: 7
